import Script from "next/script";
import "./globals.css";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen max-w-dvh overflow-hidden flex flex-col bg-black">
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
        <div className="flex-1 flex flex-col p-2">{children}</div>
        <footer className="sticky bottom-0 w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
